name: Codex - Issue to PR

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  codex_issue_to_pr:
    # Only run when the issue is labeled "codex"
    if: github.event.label.name == 'codex' &&
        (github.event.issue.author_association == 'OWNER' ||
         github.event.issue.author_association == 'MEMBER' ||
         github.event.issue.author_association == 'COLLABORATOR')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Render prompt into a temp file
        shell: bash
        run: |
          mkdir -p .codex_tmp
          python - << 'PY'
          import os
          from pathlib import Path

          template = Path(".github/codex/prompts/implement-issue.md").read_text(encoding="utf-8")
          title = os.environ["ISSUE_TITLE"]
          body = os.environ["ISSUE_BODY"]

          rendered = (template
            .replace("{{ISSUE_TITLE}}", title)
            .replace("{{ISSUE_BODY}}", body)
          )

          Path(".codex_tmp/prompt.md").write_text(rendered, encoding="utf-8")
          PY
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Run Codex
        id: run_codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt-file: .codex_tmp/prompt.md
          # For repo creation / code edits:
          sandbox: workspace-write
          safety-strategy: drop-sudo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: ${{ github.event.issue.title }}
          body: |
            Implements #${{ github.event.issue.number }}

            Auto-generated by Codex from issue text.
          branch: codex/issue-${{ github.event.issue.number }}
          commit-message: "codex: implement issue #${{ github.event.issue.number }}"